/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app.projects.$projectId.index'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/_app.projects.$projectId.settings'
import { Route as AppProjectsProjectIdMeetingsRouteImport } from './routes/_app.projects.$projectId.meetings'
import { Route as AppProjectsProjectIdIssuesRouteImport } from './routes/_app.projects.$projectId.issues'
import { Route as AppProjectsProjectIdDirectoryRouteImport } from './routes/_app.projects.$projectId.directory'
import { Route as AppProjectsProjectIdDecisionsRouteImport } from './routes/_app.projects.$projectId.decisions'
import { Route as AppProjectsProjectIdActionItemsRouteImport } from './routes/_app.projects.$projectId.action-items'
import { Route as AppProjectsProjectIdMeetingsMeetingIdRouteImport } from './routes/_app.projects.$projectId.meetings.$meetingId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdMeetingsRoute =
  AppProjectsProjectIdMeetingsRouteImport.update({
    id: '/meetings',
    path: '/meetings',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdIssuesRoute =
  AppProjectsProjectIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDirectoryRoute =
  AppProjectsProjectIdDirectoryRouteImport.update({
    id: '/directory',
    path: '/directory',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdDecisionsRoute =
  AppProjectsProjectIdDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdActionItemsRoute =
  AppProjectsProjectIdActionItemsRouteImport.update({
    id: '/action-items',
    path: '/action-items',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdMeetingsMeetingIdRoute =
  AppProjectsProjectIdMeetingsMeetingIdRouteImport.update({
    id: '/$meetingId',
    path: '/$meetingId',
    getParentRoute: () => AppProjectsProjectIdMeetingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectId/action-items': typeof AppProjectsProjectIdActionItemsRoute
  '/projects/$projectId/decisions': typeof AppProjectsProjectIdDecisionsRoute
  '/projects/$projectId/directory': typeof AppProjectsProjectIdDirectoryRoute
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
  '/projects/$projectId/meetings': typeof AppProjectsProjectIdMeetingsRouteWithChildren
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/meetings/$meetingId': typeof AppProjectsProjectIdMeetingsMeetingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectId/action-items': typeof AppProjectsProjectIdActionItemsRoute
  '/projects/$projectId/decisions': typeof AppProjectsProjectIdDecisionsRoute
  '/projects/$projectId/directory': typeof AppProjectsProjectIdDirectoryRoute
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
  '/projects/$projectId/meetings': typeof AppProjectsProjectIdMeetingsRouteWithChildren
  '/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/meetings/$meetingId': typeof AppProjectsProjectIdMeetingsMeetingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectId/action-items': typeof AppProjectsProjectIdActionItemsRoute
  '/_app/projects/$projectId/decisions': typeof AppProjectsProjectIdDecisionsRoute
  '/_app/projects/$projectId/directory': typeof AppProjectsProjectIdDirectoryRoute
  '/_app/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRoute
  '/_app/projects/$projectId/meetings': typeof AppProjectsProjectIdMeetingsRouteWithChildren
  '/_app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/meetings/$meetingId': typeof AppProjectsProjectIdMeetingsMeetingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/action-items'
    | '/projects/$projectId/decisions'
    | '/projects/$projectId/directory'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/meetings'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
    | '/projects/$projectId/meetings/$meetingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/projects'
    | '/projects/$projectId/action-items'
    | '/projects/$projectId/decisions'
    | '/projects/$projectId/directory'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/meetings'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/meetings/$meetingId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/projects/$projectId'
    | '/_app/projects/'
    | '/_app/projects/$projectId/action-items'
    | '/_app/projects/$projectId/decisions'
    | '/_app/projects/$projectId/directory'
    | '/_app/projects/$projectId/issues'
    | '/_app/projects/$projectId/meetings'
    | '/_app/projects/$projectId/settings'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/meetings/$meetingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/settings': {
      id: '/_app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/meetings': {
      id: '/_app/projects/$projectId/meetings'
      path: '/meetings'
      fullPath: '/projects/$projectId/meetings'
      preLoaderRoute: typeof AppProjectsProjectIdMeetingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/issues': {
      id: '/_app/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/directory': {
      id: '/_app/projects/$projectId/directory'
      path: '/directory'
      fullPath: '/projects/$projectId/directory'
      preLoaderRoute: typeof AppProjectsProjectIdDirectoryRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/decisions': {
      id: '/_app/projects/$projectId/decisions'
      path: '/decisions'
      fullPath: '/projects/$projectId/decisions'
      preLoaderRoute: typeof AppProjectsProjectIdDecisionsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/action-items': {
      id: '/_app/projects/$projectId/action-items'
      path: '/action-items'
      fullPath: '/projects/$projectId/action-items'
      preLoaderRoute: typeof AppProjectsProjectIdActionItemsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/meetings/$meetingId': {
      id: '/_app/projects/$projectId/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/projects/$projectId/meetings/$meetingId'
      preLoaderRoute: typeof AppProjectsProjectIdMeetingsMeetingIdRouteImport
      parentRoute: typeof AppProjectsProjectIdMeetingsRoute
    }
  }
}

interface AppProjectsProjectIdMeetingsRouteChildren {
  AppProjectsProjectIdMeetingsMeetingIdRoute: typeof AppProjectsProjectIdMeetingsMeetingIdRoute
}

const AppProjectsProjectIdMeetingsRouteChildren: AppProjectsProjectIdMeetingsRouteChildren =
  {
    AppProjectsProjectIdMeetingsMeetingIdRoute:
      AppProjectsProjectIdMeetingsMeetingIdRoute,
  }

const AppProjectsProjectIdMeetingsRouteWithChildren =
  AppProjectsProjectIdMeetingsRoute._addFileChildren(
    AppProjectsProjectIdMeetingsRouteChildren,
  )

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdActionItemsRoute: typeof AppProjectsProjectIdActionItemsRoute
  AppProjectsProjectIdDecisionsRoute: typeof AppProjectsProjectIdDecisionsRoute
  AppProjectsProjectIdDirectoryRoute: typeof AppProjectsProjectIdDirectoryRoute
  AppProjectsProjectIdIssuesRoute: typeof AppProjectsProjectIdIssuesRoute
  AppProjectsProjectIdMeetingsRoute: typeof AppProjectsProjectIdMeetingsRouteWithChildren
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdActionItemsRoute: AppProjectsProjectIdActionItemsRoute,
  AppProjectsProjectIdDecisionsRoute: AppProjectsProjectIdDecisionsRoute,
  AppProjectsProjectIdDirectoryRoute: AppProjectsProjectIdDirectoryRoute,
  AppProjectsProjectIdIssuesRoute: AppProjectsProjectIdIssuesRoute,
  AppProjectsProjectIdMeetingsRoute:
    AppProjectsProjectIdMeetingsRouteWithChildren,
  AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
